<a href="https://colab.research.google.com/github/luizasantana258-crypto/Inteligencia_Artificial_LuizaSantana_6-D_Matutino/blob/main/Atividade_DataScience_LuizaSantana_6%C2%BAD_Matutino.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercícios NumPy




1. Crie um array unidimensional de 50 elementos contendo números inteiros aleatórios entre 10 e 100.

In [ ]:
import numpy as np  # Importa a biblioteca numpy com o apelido np

n=np.random.randint(10, 101, 50)  # Gera 50 números inteiros aleatórios entre 10 e 100
print(n)  # Exibe o array gerado

[62 83 94 27 55 56 34 85 84 46 98 48 41 84 70 77 12 58 86 38 69 73 13 46
 39 33 21 77 38 38 18 24 75 97 16 29 10 48 79 52 21 17 36 86 92 28 11 62
 48 80]


Um array n foi criado com 50 números inteiros aleatórios entre 10 e 100 utilizando np.random.randint(). O valor 101 é usado porque o limite superior não é incluído.

2. Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última linha.

In [ ]:
import numpy as np

matriz=np.arange(1, 17).reshape(4, 4)  # Cria uma sequência de 1 a 16 e a organiza em uma matriz 4x4
ultimaLinha=matriz[-1]  # Seleciona a última linha da matriz

print(matriz)
print(ultimaLinha)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[13 14 15 16]


Uma sequência de números de 1 a 16 foi criada utilizando np.arange() e depois organizada em uma matriz 4x4 utilizando reshape(). Em seguida, matriz[-1] selecionou a última linha da matriz, pois o índice -1 representa o último elemento. O resultado foi armazenado em ultimaLinha.


3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª `a 10ª posição por 1.

In [ ]:
import numpy as np

array=np.zeros(15)  # Cria um array com 15 posições preenchidas com zero
array[4:10]=1  # Substitui da 5ª até a 10ª posição pelo valor 1

print(array)

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


Um array com 15 posições preenchidas com zero foi criado utilizando np.zeros(). Depois, o fatiamento array[4:10] selecionou as posições do índice 4 até o índice 9, que correspondem à 5ª até a 10ª posição. Essas posições foram substituídas pelo valor 1.

4. Gere um array de 100 números inteiros aleatórios e encontre a mediana e a moda dos valores.

In [ ]:
import numpy as np

array=np.random.randint(1, 101, 100)
mediana=np.median(array)  # Calcula a mediana dos valores
valores, contagem=np.unique(array, return_counts=True)  # Conta a frequência de cada valor único no array
moda=valores[np.argmax(contagem)]  # Identifica a moda

print(array)
print('Mediana:', mediana)
print('Moda:', moda)


[54 57 18 90 13 72 49 33 74 64 93 30  9 25 98 80 50 97 29 56  3 45 55 35
 60 86 52 33 20 77 96 83 88 48  7 67 75 72 43 79 33 28 35 77 93  3 84 46
 63 93 99 35 82 35 57 42 48 74 44 21 91 48 51 18 39 89 72 66 36 55 90 70
 69 57 34 94 23 72 51 40 63 47 14  3 19 79 88 21 64 99 29 75 61 67 11 16
 38 27 46 59]
Mediana: 54.5
Moda: 35


Um array foi criado com 100 números inteiros aleatórios entre 1 e 100 utilizando np.random.randint(). Depois, np.median() calculou a mediana dos valores do array.
Em seguida, np.unique() identificou os valores que aparecem no array e, com return_counts=True, também contou quantas vezes cada valor aparece. Esses resultados foram armazenados em valores e contagem. Depois, np.argmax() encontrou a posição da maior contagem, e essa posição foi usada para encontrar a moda em valores.

5. Crie um array de 20 elementos contendo números entre 1 e 100 e substitua todos os valores múltiplos de 3 por -3.

In [ ]:
import numpy as np

array=np.random.randint(1, 101, 20)
arrayOriginal=array.copy()  # Cria uma cópia dos valores originais
array[array % 3 == 0] = -3  # Substitui os múltiplos de 3 pelo valor -3

print('Antes:')
print(arrayOriginal)
print('\nDepois:')
print(array)

Antes:
[13  3 64 96 98  8 71 47 53 54 86 79  3 96 56 95 62 92 22 83]

Depois:
[13 -3 64 -3 98  8 71 47 53 -3 86 79 -3 -3 56 95 62 92 22 83]


Um array foi criado com 20 números inteiros aleatórios entre 1 e 100 utilizando np.random.randint(). Depois, array.copy() criou uma cópia do array original para manter os valores antes da alteração. Em seguida, a condição array % 3 == 0 identificou os valores divisíveis por 3, e esses valores foram substituídos por -3. Por fim, os arrays antes e depois da alteração foram exibidos utilizando print().


6. Gere uma matriz 5x5 de números aleatórios entre 0 e 1 e encontre a soma de cada coluna.

In [ ]:
import numpy as np

matriz=np.round(np.random.rand(5, 5), 2)  # Gera uma matriz 5x5 com valores aleatórios entre 0 e 1 e arredonda para 2 casas decimais

print('Matriz:')
print(matriz)

somaColunas=np.round(np.sum(matriz, axis=0), 2)  # Soma os valores de cada coluna e arredonda o resultado

print('Soma das colunas:')
print(somaColunas)

Matriz:
[[0.26 0.8  0.37 0.15 0.73]
 [0.96 0.89 0.57 0.76 0.69]
 [0.35 0.83 0.34 0.38 0.44]
 [0.79 0.53 0.18 0.92 0.34]
 [0.7  0.81 0.47 0.5  0.06]]
Soma das colunas:
[3.06 3.86 1.93 2.71 2.26]


Uma matriz 5x5 foi criada com valores aleatórios entre 0 e 1 utilizando np.random.rand(), e np.round() arredondou os valores para duas casas decimais. Depois, np.sum() foi utilizada com axis=0 para somar os valores de cada coluna, e np.round() arredondou os resultados para duas casas decimais. Por fim, a matriz e a soma de cada coluna foram exibidas utilizando print().


7. Crie dois arrays de números aleatórios e encontre a correlação entre eles.

In [ ]:
import numpy as np

array1 = np.random.randint(1, 101, 10)
array2 = np.random.randint(1, 101, 10)

print('Array 1:')
print(array1)
print('\nArray 2:')
print(array2)

correlacao=np.corrcoef(array1, array2)[0, 1]  # Calcula a correlação entre os dois arrays

print('\nCorrelação:')
print(round(correlacao, 2))

Array 1:
[56 73 70 60 37 17 60 44 32 22]

Array 2:
[35 33 90 65 61 88 66 30 82 72]

Correlação:
-0.37


Dois arrays foram criados com 10 números inteiros aleatórios entre 1 e 100 utilizando np.random.randint(). Depois, np.corrcoef() calculou a correlação entre os dois arrays, e [0, 1] selecionou o valor da correlação entre eles. O resultado foi armazenado na variável correlacao. Por fim, round() arredondou a correlação para duas casas decimais e print() exibiu o resultado.


8. Gere uma matriz 3x3 com números inteiros aleatórios e eleve todos os seus elementos ao quadrado.

In [ ]:
import numpy as np

matriz=np.random.randint(1, 11, size=(3, 3))
matrizQuadrada=matriz ** 2  # Eleva todos os elementos da matriz ao quadrado

print('Matriz original:')
print(matriz)
print('Matriz ao quadrado:')
print(matrizQuadrada)

Matriz original:
[[7 7 8]
 [3 3 4]
 [6 1 7]]
Matriz ao quadrado:
[[49 49 64]
 [ 9  9 16]
 [36  1 49]]


Uma matriz 3x3 foi criada com números inteiros aleatórios entre 1 e 10 utilizando np.random.randint(). Depois, todos os elementos da matriz foram elevados ao quadrado utilizando a operação matriz ** 2. O resultado foi armazenado em matrizQuadrada. Por fim, a matriz original e a matriz ao quadrado foram exibidas utilizando print().


9. Crie um array com 10 números aleatórios e normalize seus valores entre 0
e 1.

In [ ]:
import numpy as np

array=np.round(np.random.rand(10), 2)

normalizado=(array - np.min(array)) / (np.max(array) - np.min(array))  # Aplica a fórmula de normalização min-max

print('Array original:')
print(array)

print('\nArray normalizado:')
print(np.round(normalizado, 2))

Array original:
[0.95 0.87 0.79 0.64 0.38 0.94 0.82 0.25 0.72 0.53]

Array normalizado:
[1.   0.89 0.77 0.56 0.19 0.99 0.81 0.   0.67 0.4 ]


Um array com 10 números aleatórios entre 0 e 1 foi criado utilizando np.random.rand(), e np.round() arredondou os valores para duas casas decimais. Depois, a normalização min-max foi aplicada ao array, fazendo com que o menor valor se aproxime de 0 e o maior valor de 1, enquanto os demais são ajustados proporcionalmente entre esses limites. Por fim, os valores originais e os valores normalizados foram exibidos, sendo os normalizados arredondados para duas casas decimais.


10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescentes de 1 a 6.

In [ ]:
import numpy as np

matriz=np.eye(6)  # Cria uma matriz identidade 6x6

# Substitui a diagonal principal pelos valores 1, 2, 3, 4, 5 e 6
np.fill_diagonal(matriz, np.arange(1, 7))

print('Matriz identidade:')
print(matriz)

print('\nMatriz alterada:')
print(matriz)

Matriz identidade:
[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]

Matriz alterada:
[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


Uma matriz identidade 6x6 foi criada utilizando np.eye(), onde a diagonal principal recebe inicialmente o valor 1 e os demais valores são 0. Depois, np.arange() criou os valores de 1 a 6, e np.fill_diagonal() substituiu os valores da diagonal principal por esses números.


11. Gere um array de 100 números inteiros e encontre o valor que mais se repete no array.

In [ ]:
import numpy as np

array=np.random.randint(1, 21, 100)

valores, contagens=np.unique(array, return_counts=True) # Função definida como true para retornar dois arrays: um com os números únicos encontrados e outro com a quantidade de vezes que cada um apareceu.

indice=np.argmax(contagens) # Retorna o índice do números do valor máximo do array

moda=valores[indice]

print(f'A Array: {array} tem o número {moda} como moda.')

A Array: [19  2 17 11  8 10 15 18  1 14 17 16  5 20 13  3 17  8  3  4  6  5  6 11
 12  4  7  2 13 19  7  9  3  1  2  8  2 14  5  3  4  3  3 12 19 13 11 16
  1 13  3  3 11  3  8 10  1  1 19  2  9 11 15 13  7  3  6 15  7 14  5 10
  5 10 20  7 10 17  1 16 15 15 20  9 20 11  6 20 11 15 18  8  3 16  6 14
 19 12  6 11] tem o número 3 como moda.


Usando a função 'np.random.randint' foi gerado um array com números aleatórios do 1 ao 20, com um limite de 100 elemetos, com as funções 'unique' + 'return_counsts=true' e com o array principal como parâmetro foi gerado mais dois array, uma com os números unicos encontrados e outro com a contagem da frequência desses números. Depois, em uma variável chamada 'indice', foi armazenado o índice do valor máximo do array de contagens, e por fim, a variável 'moda' captura o valor com a maior contagem no array de valores.

12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.

In [ ]:
import numpy as np

matriz=np.random.randint(1, 10, size=(4, 4)) # Cria uma matriz com o valores mínimo 1 e o máximo 10 de tamanho 4x4
print(f'Antes:\n{matriz}\n')

for n in range(len(matriz)): # Percorre cada linha da matriz
  matriz[n][n]=7 # Substitui o elemento da diagonal principal por 7

print(f'Depois:\n{matriz}')


Antes:
[[1 6 6 8]
 [4 3 2 3]
 [2 6 7 4]
 [2 4 5 5]]

Depois:
[[7 6 6 8]
 [4 7 2 3]
 [2 6 7 4]
 [2 4 5 7]]


A matriz 4x4 foi criada com números aleatórios de 1 a 10, o for in percorre cada linha da matriz e já que na diagonal da matriz, o índice da linha e da coluna são iguais, é usado a quantidade de linhas da matriz para controle do índice de linha e coluna que deve ser igual a 7.

13. Crie um array contendo os 10 primeiros números pares e calcule sua soma cumulativa.

In [ ]:
import numpy as np

pares=np.linspace(2, 20, 10) # Cria um array com elementos espaçados uniformemente entre 2 e 20, com um total de 10 elementos.

soma=np.cumsum(pares) # Calcula a soma cumulativa dos elementos
print(f'A soma cumulativa do array {pares} é {soma}')


A soma cumulativa do array [ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.] é [  2.   6.  12.  20.  30.  42.  56.  72.  90. 110.]


Foi armazenado os 10 primeiros números pares no array e depois a função cumsum() somou todos os elementos anteriores colocando o resultado na posição correspondente.

14. Calcule a diferença entre dois arrays de números aleatórios de mesmo comprimento e encontre a média das diferenças.

In [ ]:
import numpy as np

array1=np.random.randint(1, 10, 10)
array2=np.random.randint(1, 10, 10)

diferenca=np.subtract(array1, array2) # Calcula a diferença entre cada elemento do array
media=np.mean(diferenca) # Calcula a média das diferenças

print(f'Array 1: {array1}\nArray 2: {array2}\nDiferença: {diferenca}\nMédia: {media}')

Array 1: [5 7 5 3 7 3 7 3 6 6]
Array 2: [2 8 4 7 2 3 8 8 5 5]
Diferença: [ 3 -1  1 -4  5  0 -1 -5  1  1]
Média: 0.0


Os dois arrays foram criados com a função np.random.randint, armazenado números de 1 a 10 com total de 10 elementos. Com a função np.subtract foi calculado a diferença dos arrays e com a função np.mean foi calculado a média das diferenças.

15. Gere um array contendo 20 números e substitua todos os valores maiores que 50 por 50.

In [ ]:
import numpy as np

array=np.random.randint(1, 100, 20)
print(f'Antes:\n{array}\n')

for i in range(len(array)):  # Percorre cada índice do array

  if array[i] > 50: # Verifica se o valor atual é maior que 50
    array[i]=50 # Se sim, substitui o valor por 50

print(f'Depois:\n{array}')

Antes:
[31  1 77 39 49 39 91 83 85 17 36 50  8 85 80 43 49 53 48 41]

Depois:
[31  1 50 39 49 39 50 50 50 17 36 50  8 50 50 43 49 50 48 41]


O array foi gerado com números aleatórios de 1 a 100 com 20 elementos no total, o for in percorreu o índice de cada elemento, usando o tamanho do array como parâmetro e verificando se o valor do índice atual é maior que 50, se sim, substitui o valor por 50.

16. Crie um array unidimensional e reorganize seus valores em uma matriz 3x4.

In [ ]:
import numpy as np

array=np.random.randint(1, 10, 12)
print(f'Array:\n{array}\n')

matriz=array.reshape(3, 4) # Redimenciona o array em uma matriz 3x4
print(f'Matriz:\n{matriz}')

Array:
[2 3 2 3 5 7 5 6 9 9 6 9]

Matriz:
[[2 3 2 3]
 [5 7 5 6]
 [9 9 6 9]]


Array unidimensional criada com números aleatórios de 1 a 10 com um total de 12 elemento, depois redimensionada em um matriz 3x4 com a função reshape().

17. Gere uma matriz 4x4 de números inteiros aleatórios e multiplique cada valor por sua posição na matriz.

In [ ]:
import numpy as np

matriz=np.random.randint(1, 10, size=(4, 4))

posicoes=np.arange(16).reshape(4, 4) # Cria um array como elementos do 0 ao 15 em tranforma em matriz 4x4

multiplicada=np.multiply(matriz, posicoes) # Multiplica cada elemento da matriz original pela posição correspondente

print(f'Matriz original:\n{matriz}\n')
print(f'Matriz Multiplicada:\n{multiplicada}')

Matriz original:
[[1 4 7 5]
 [9 1 1 1]
 [7 7 9 3]
 [5 2 9 6]]

Matriz Multiplicada:
[[  0   4  14  15]
 [ 36   5   6   7]
 [ 56  63  90  33]
 [ 60  26 126  90]]


A matriz original foi criada com números aleatórios de 1 a 10 com o tamanho 4x4, a matriz da posições foi criada com 16 elementos sendo eles a representação do índice de cada número da matriz original. Depois a multiplicação foi feita com a função np.multiply() que multiplica uma array pela outra.

18. Crie um array de 10 elementos contendo números entre 1 e 100 e substitua
todos os valores múltiplos de 5 por 0.

In [ ]:
import numpy as np

array=np.random.randint(1, 101, 10)
print(f'Antes:\n{array}\n')

for i in range(len(array)):

  if array[i] % 5 == 0: # Verifica se o restante da divisão é igual a zero
    array[i]=0 #Se sim, substitui o valor por 0

print(f'Depois:\n{array}')

Antes:
[74 61 84 33 16 86 44 26 79 45]

Depois:
[74 61 84 33 16 86 44 26 79  0]


O array foi gerado com números aleatórios de 1 a 101 com 10 elementos no total, o for in percorreu o índice de cada elemento, usando o tamanho do array como parâmetro e verificando se o valor do índice atual é divisível por 5, se sim, substitui por 0.

19. Crie dois arrays de números inteiros aleatórios de tamanho 20 e calcule o
ângulo entre eles (produto escalar normalizado).

In [ ]:
import numpy as np

array1=np.random.randint(1, 10, 20)
array2=np.random.randint(1, 10, 20)

produtoEscalar=np.dot(array1, array2) # Calcula o produto escalar

# Calcular os comprimentos dos vetores
comprimentoA=np.sqrt(np.dot(array1, array1))
comprimentoB=np.sqrt(np.dot(array2, array2))

anguloCos=produtoEscalar / (comprimentoA * comprimentoB) # Calcula o cosseno do ângulo (produto escalar normalizado)

# Encontrar o ângulo em radianos e converter para graus
angulo_rad=np.arccos(anguloCos)
angulo_graus=np.degrees(angulo_rad)

print(f"Produto Escalar: {produtoEscalar}")
print(f"Ângulo em graus: {angulo_graus:.2f}°")


Produto Escalar: 531
Ângulo em graus: 35.60°


Dois arrays unidimensionais foram criados com números inteiros aleatórios de 1 a 9, com um total de 20 elementos cada. Depois, foi calculado o produto escalar entre os dois arrays com a função np.dot(). Em seguida, foi calculado o comprimento de cada vetor usando a raiz quadrada do produto escalar do próprio vetor. Com esses valores, foi calculado o cosseno do ângulo através da divisão do produto escalar pelo produto dos comprimentos dos vetores. Por fim, foi utilizada a função np.arccos() para encontrar o ângulo em radianos e np.degrees() para converter o resultado para graus, sendo exibido o produto escalar e o ângulo com duas casas decimais.


20. Crie uma matriz de números inteiros e encontre o valor mínimo de cada
linha.


In [ ]:
import numpy as np

matriz=np.random.randint(1, 10, size=(4, 2))

for linha in matriz:
  minimo=np.min(linha) # Encontra o valor mínimo da linha atual
  print(f'O valor mínimo da linha{linha} é {minimo}')

O valor mínimo da linha[2 3] é 2
O valor mínimo da linha[5 5] é 5
O valor mínimo da linha[9 1] é 1
O valor mínimo da linha[6 4] é 4


A matriz foi criada com números aleatórios de 1 a 10 com o tamanho 4x2, o for in percorre cada linha da matriz, e com a função np.min() captura o valor mínimo da linha e exibe.

## Exercícios SciPy

1. Calcule a integral da função f(x) = x^2 sin(x) no intervalo de 0 a π.

In [ ]:
import numpy as np
from scipy import integrate

# Define a função a ser integrada
def f(x):
    return (x**2) * np.sin(x)

# Calcula a integral de 0 a pi (np.pi)
resultado, erro = integrate.quad(f, 0, np.pi)

print("Resultado da integral:",resultado)
print("Erro estimado:",erro)

Resultado da integral: 5.869604401089359
Erro estimado: 6.516569951530559e-14


Uma função f(x) foi criada para representar a expressão x² · sen(x), utilizando np.sin() para calcular o seno. Depois, a função integrate.quad() da biblioteca SciPy foi utilizada para calcular a integral definida de 0 até π, passando a função e os dois limites como parâmetros. O resultado da integral e uma estimativa do erro do cálculo foram armazenados nas variáveis resultado e erro, respectivamente, sendo exibidos ao final.


2.  Resolva a equação diferencial dy/dx = x - y, com y(0) = 1, no intervalo de 0 a 10.

In [ ]:
import numpy as np
from scipy.integrate import solve_ivp

# Define a equação diferencial dy/dx = x - y
def f(x, y):
    return x - y

# Define o intervalo de 0 a 10 e a condição inicial y(0) = 1
intervalo=[0, 10]
y0=[1]

# Gera 100 pontos para avaliar a solução no intervalo
x_pontos=np.linspace(0, 10, 100)

solucao=solve_ivp(f, intervalo, y0, t_eval=x_pontos)

print("Valores de x:",solucao.t)
print("Soluções para y:",solucao.y)

Valores de x: [ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808 

Uma função foi criada para representar a equação diferencial dy/dx = x - y, depois foi definido o intervalo de 0 a 10 e a condição inicial y(0) = 1. Em seguida, a função linspace() foi utilizada para gerar 100 pontos igualmente espaçados entre 0 e 10. A função solve_ivp() foi utilizada para resolver a equação diferencial, passando como parâmetros a função, o intervalo, a condição inicial e os pontos onde a solução será avaliada. Por fim, foram exibidos os valores de x e as respectivas soluções de y.

3. Encontre as raízes da função f(x) = x^4 - 3x^3 + 2 utilizando SciPy.


In [ ]:
import numpy as np
from scipy.optimize import fsolve

def f(x):
    return x**4 - 3*x**3 + 2

# Encontra uma raiz partindo de um palpite inicial (ex: x = 1)
raiz1=fsolve(f, 1.0)
# Encontra outra raiz partindo de outro palpite (ex: x = 3)
raiz2=fsolve(f, 3.0)

print(f"Raiz encontrada próxima de 1: {raiz1}")
print(f"Raiz encontrada próxima de 3: {raiz2}")

Raiz encontrada próxima de 1: [1.]
Raiz encontrada próxima de 3: [2.91963957]


Uma função foi criada para representar a equação x⁴ - 3x³ + 2, que será utilizada para encontrar os valores de x que fazem a função ser igual a zero. Depois, a função fsolve() da biblioteca scipy.optimize foi utilizada para encontrar as raízes da equação, passando como parâmetros a função f e um palpite inicial para indicar aproximadamente onde procurar a raiz. A primeira raiz foi procurada partindo do valor 1.0 e armazenada em raiz_1, enquanto a segunda foi procurada partindo do valor 3.0 e armazenada em raiz_2. Por fim, os valores das raízes encontradas foram exibidos utilizando print().


4. Use a função de otimização de SciPy para maximizar f(x) = -x^2 + 4x + 1.

In [ ]:
from scipy.optimize import minimize

# Para maximizar, precisa usar a função negativa
def f_negativa(x):
    return -(x**2 - 4*x - 1)

# Encontra o mínimo da função negativa partindo de x = 0
resultado=minimize(f_negativa, 0)

# Pega o valor de x dentro do array
ponto_maximo=resultado.x[0]
# Inverte o sinal para obter o valor da função original
valor_maximo=-resultado.fun

print(f"O ponto de máximo encontrado é x = {ponto_maximo:.2f}")
print(f"O valor máximo de f(x) é {valor_maximo:.2f}")

O ponto de máximo encontrado é x = -1034.24
O valor máximo de f(x) é 1073788.34


Uma função foi criada para representar x² - 4x - 1, depois a função minimize() da biblioteca scipy.optimize foi utilizada para encontrar o menor valor da função, partindo de um palpite inicial x = 0. O resultado foi armazenado em resultado, que contém o ponto onde o menor valor foi encontrado e o valor da função nesse ponto. Em seguida, resultado.x[0] foi utilizado para pegar o primeiro valor do array retornado pelo minimize(), armazenando o ponto de mínimo em ponto_minimo, enquanto resultado.fun armazena o valor mínimo encontrado pela função. Por fim, os dois valores foram exibidos utilizando print(), com :.2f para mostrar apenas duas casas decimais.

5. Calcule a transformada de Fourier de um sinal composto de sin(2πt) e
cos(4πt).


In [ ]:
import numpy as np
from scipy.fft import fft

# Cria o intervalo de tempo (0 a 1 segundo, com 500 amostras)
t=np.linspace(0, 1, 500)

# Define o sinal composto de sin(2*pi*t) e cos(4*pi*t), O sinal é a soma das duas frequências
sinal=np.sin(2 * np.pi * t) + np.cos(4 * np.pi * t)

# Calcula a transformada de Fourier (FFT)
frequencias=fft(sinal)

print("Transformada de Fourier (primeiros 5 valores):")
print(frequencias[:5])


Transformada de Fourier (primeiros 5 valores):
[  1.          -0.j           2.90072788-249.73479714j
 250.21550029  +3.81342503j  -0.81269128  +0.36070345j
  -0.34169494  +0.25879207j]


Um intervalo de tempo foi criado com a função np.linspace(), gerando 500 pontos igualmente espaçados entre 0 e 1 segundo. Depois, foi criado um sinal composto pela soma de duas ondas, uma utilizando np.sin() com frequência de 1 Hz e outra utilizando np.cos() com frequência de 2Hz. Em seguida, a função fft() da biblioteca scipy.fft foi utilizada para calcular a Transformada Rápida de Fourier (FFT) do sinal, transformando o sinal do domínio do tempo para o domínio das frequências. O resultado foi armazenado em frequencias, que contém os valores das frequências presentes no sinal. Por fim, frequencias[:5] foi utilizado para selecionar e exibir apenas os 5 primeiros valores da transformada.

6. Encontre a matriz inversa de uma matriz 5x5 de números aleatorios.

In [ ]:
import numpy as np
from scipy import linalg

matriz=np.random.randint(1, 50, size=(5, 5))# Gera uma matriz 5x5 de números aleatórios entre 1 e 49

# Calcular a matriz inversa com SciPy
matriz_inversa=linalg.inv(matriz)

print("Matriz Original (5x5):\n", matriz)
print("\nMatriz Inversa:\n", matriz_inversa)

identidade=np.dot(matriz, matriz_inversa)
print("\nVerificação (Matriz Identidade):\n", np.round(identidade, 2))

Matriz Original (5x5):
 [[32 15 45 44 40]
 [40 29 22 33  6]
 [13 17 49 29 35]
 [32 14 36 28  1]
 [32 11 24 40 42]]

Matriz Inversa:
 [[-0.57147989 -0.08153266  0.19709001  0.23858611  0.38599178]
 [-0.01150722  0.05230211  0.03067756 -0.04533548 -0.02099769]
 [-0.13942403 -0.03550145  0.06919355  0.07733719  0.07835377]
 [ 0.84848964  0.11410096 -0.33384071 -0.31685223 -0.53864081]
 [-0.28998746 -0.03995909  0.12020595  0.08766504  0.20343761]]

Verificação (Matriz Identidade):
 [[ 1. -0.  0.  0.  0.]
 [-0.  1.  0.  0.  0.]
 [-0. -0.  1.  0.  0.]
 [-0. -0.  0.  1.  0.]
 [-0. -0.  0.  0.  1.]]


Uma matriz 5x5 foi criada com números aleatórios entre 0 e 1 utilizando a função np.random.rand(). Depois, a função linalg.inv() da biblioteca SciPy foi utilizada para calcular a matriz inversa da matriz criada, armazenando o resultado em matriz_inversa. Em seguida, foram exibidas a matriz original e sua matriz inversa. Por fim, foi calculado o produto entre a matriz original e a matriz inversa utilizando np.dot(), e o resultado foi armazenado em identidade. Como o produto de uma matriz pela sua inversa deve resultar em uma matriz identidade, a função np.round(identidade, 2) foi utilizada para arredondar os valores para duas casas decimais e facilitar a visualização da verificação.


7. Use a funções de interpolação cúbica de SciPy para interpolar os dados
(0, 0),(1, 2),(2, 3),(3, 5),(4, 4).

In [ ]:
import numpy as np
from scipy.interpolate import interp1d

# Define os pontos de dados conhecidos
x=np.array([0, 1, 2, 3])
y=np.array([1, 3, 2, 5])

# Cria uma função de interpolação usando um polinômio de 3º grau
f_cubica=interp1d(x, y, kind='cubic')

x_novos=np.linspace(0, 3, 7) # Gera 7 novos pontos entre 0 e 3

y_novos=f_cubica(x_novos) # Calcula os valores de y para os novos pontos

print("Novos pontos x:",x_novos)
print("Valores interpolados y:",y_novos)

Novos pontos x: [0.  0.5 1.  1.5 2.  2.5 3. ]
Valores interpolados y: [1.     2.8125 3.     2.4375 2.     2.5625 5.    ]


Um array x e um array y foram criados com 4 pontos conhecidos, sendo cada valor de x relacionado a um valor correspondente de y. Depois, a função interp1d() da biblioteca SciPy foi utilizada para criar uma função de interpolação, utilizando kind='cubic' para definir um polinômio de 3º grau. Em seguida, a função np.linspace() foi utilizada para gerar 7 novos pontos igualmente espaçados entre 0 e 3, armazenados em x_novos. Esses novos pontos foram passados para a função f_cubica() para calcular valores de y estimados a partir dos pontos conhecidos, armazenando os resultados em y_novos. Por fim, os novos pontos de x e os valores interpolados de y foram exibidos utilizando print().


8. Resolva o sistema de equações 3x + 2y = 5 e x + 4y = 6.

In [ ]:
import numpy as np
from scipy import linalg

# Define os coeficientes das equações (Matriz A)
A=np.array([[4, 5], [6, 7]])

# Define os resultados das equações (Vetor B)
B=np.array([8, 9])

solucao=linalg.solve(A, B)

print(f"Solução [x, y]: {solucao}")

Solução [x, y]: [-5.5  6. ]


Uma matriz A foi criada contendo os coeficientes das duas equações do sistema, representando os valores que acompanham x e y. Depois, um vetor B foi criado contendo os resultados das duas equações. A função linalg.solve() da biblioteca SciPy foi utilizada para resolver o sistema de equações, recebendo como parâmetros a matriz A e o vetor B, e o resultado foi armazenado em solucao. Por fim, a solução encontrada para x e y foi exibida utilizando print().

Nesse caso, a matriz e o vetor representam o sistema:
4x + 5y = 8
6x + 7y = 9
E o resultado de solucao contém os valores de x e y, nessa ordem.


9. Ajuste uma curva quadrática aos pontos (1, 2),(2, 4),(3, 5),(4, 7),(5, 8).


In [ ]:
import numpy as np
from scipy.optimize import curve_fit

# Define os pontos de dados
x_dados=np.array([3, 5, 7])
y_dados=np.array([3, 5, 9])

# Define a função modelo (curva quadrática/parábola)
def curva_quadratica(x, a, b, c):
    return a * x**2 + b * x + c

parametros, _ = curve_fit(curva_quadratica, x_dados, y_dados) # Ajusta a curva aos pontos

print("Parâmetros ajustados [a, b, c]:")
print(parametros)

Parâmetros ajustados [a, b, c]:
[ 0.25 -1.    3.75]


/tmp/ipykernel_3576/2308185068.py:12: OptimizeWarning: Covariance of the parameters could not be estimated
  parametros, _ = curve_fit(curva_quadratica, x_dados, y_dados) # Ajusta a curva aos pontos


Um array x_dados e um array y_dados foram criados contendo 3 pontos correspondentes, onde cada valor de x possui um valor de y. Depois, foi criada a função curva_quadratica() para representar uma função quadrática no formato a*x² + b*x + c, recebendo x, a, b e c como parâmetros. Em seguida, a função curve_fit() da biblioteca SciPy foi utilizada para ajustar a curva quadrática aos pontos fornecidos, passando como parâmetros a função modelo, os valores de x e os valores correspondentes de y. Os valores encontrados para a, b e c foram armazenados em parametros, enquanto _ recebe um segundo resultado da função que não será utilizado. Por fim, os parâmetros ajustados foram exibidos utilizando print().


10. Calcule a integral dupla da funções f(x, y) = xy + x^2 no intervalo [0, 2]
para x e [0, 1] para y.


In [ ]:
import numpy as np
from scipy.integrate import dblquad

def f(y, x):
    return x * y + x**2

# Calcular a integral dupla
# Limites de x: 0 a 2
# Limites de y: 0 a 1
resultado, erro = dblquad(f, 0, 2, 0, 1)

print(f"Resultado da integral dupla: {resultado:.4f}")
print(f"Erro estimado: {erro}")

Resultado da integral dupla: 3.6667
Erro estimado: 5.5294392329864537e-14


Uma função f(y, x) foi criada para representar a função xy + x², recebendo y e x como parâmetros e retornando o resultado da expressão. Depois, a função dblquad() da biblioteca SciPy foi utilizada para calcular a integral dupla, passando como parâmetros a função, os limites externos de x de 0 a 2 e os limites internos de y de 0 a 1. Na definição da função, y aparece primeiro porque a dblquad() espera os argumentos na ordem (y, x), mesmo que matematicamente normalmente escrevamos f(x, y). O resultado da integral e o erro estimado foram armazenados nas variáveis resultado e erro. Por fim, o resultado foi exibido com :.4f, mostrando 4 casas decimais, e o erro estimado também foi exibido.

11. Encontre os autovalores e autovetores de uma matriz 4x4 de números inteiros aleatórios.

In [ ]:
import numpy as np
from scipy.linalg import eig

matriz=np.random.randint(1, 10, (4, 4))
autovalores, autovetores=eig(matriz)   # Calcula os autovalores e autovetores

print(matriz)

print('\nAutovalores:')
print(autovalores)

print('\nAutovetores:')
print(autovetores)

[[6 2 4 4]
 [3 7 7 8]
 [3 2 7 3]
 [3 5 3 5]]

Autovalores:
[17.70251549+0.j -0.55759959+0.j  4.40652787+0.j  3.44855622+0.j]

Autovetores:
[[ 0.403351    0.22711081  0.28247419  0.3498026 ]
 [ 0.69908572  0.65248359 -0.49571523  0.10135915]
 [ 0.37217706  0.02400432  0.64443035 -0.78106081]
 [ 0.45833542 -0.72257155 -0.50910143  0.50725582]]


Uma matriz 4x4 foi criada com números inteiros aleatórios entre 1 e 9 utilizando np.random.randint(). Depois, eig() foi utilizada para calcular os autovalores e autovetores da matriz. Os resultados foram separados nas variáveis autovalores e autovetores. Por fim, a matriz original, os autovalores e os autovetores foram exibidos utilizando print().


12. Resolva a equação e ** x - x ** 2 = 0 para encontrar a raiz mais próxima de x = 1.

In [ ]:
import numpy as np
from scipy.optimize import fsolve

def funcao(x):  # Define a função
    return np.exp(x) - x**2

raiz=fsolve(funcao, 1)  # Busca a raiz mais próxima de x = 1

print(raiz)

[-0.70346742]


Uma função foi criada para representar a equação e calcular o valor de e^x - x² para cada valor de x. Depois, fsolve() foi utilizada para encontrar uma raiz da função, começando a busca a partir do valor inicial x = 1. O resultado foi armazenado na variável raiz e depois exibido utilizando print().


13. Calcule o determinante de uma matriz 6x6 de números aleatórios entre -10 e 10.

In [ ]:
import numpy as np
from scipy.linalg import det

matriz=np.random.randint(-10, 11, (6, 6))

determinante=det(matriz) # Calcula o determinante da matriz

print(matriz)
print('\nDeterminante:')
print(determinante)

[[-6 10  3 -2 -6  2]
 [-3  0  1 -5  1 -2]
 [10  3  7 -7 -7  7]
 [-3  3  3  9  2 -6]
 [ 3  3 -6 -2  3  7]
 [ 9 -7  7 -1 -3 -9]]

Determinante:
-390300.99999999994


Uma matriz 6x6 foi criada com números inteiros aleatórios entre -10 e 10 utilizando np.random.randint(). Depois, det() foi utilizada para calcular o determinante dessa matriz. O resultado foi armazenado na variável determinante.


14. Utilize uma função de otimização multivariada para minimizar f(x, y) = (x - 2)**2 + (y - 3)**2.


In [ ]:
from scipy.optimize import minimize

def funcao(p):
    x, y = p
    return (x - 2)**2 + (y - 3)**2

resultado=minimize(funcao, [0, 0])  # Inicia a busca em x=0 e y=0

print(resultado.x)

[1.99999999 2.99999999]


Uma função foi criada para calcular o valor de uma expressão que depende de duas variáveis, x e y. Depois, minimize() foi utilizada para encontrar os valores de x e y que produzem o menor resultado possível da função, começando a busca pelo ponto [0, 0]. O resultado foi armazenado na variável resultado, e resultado.x retorna os valores de x e y encontrados no ponto de mínimo. Por fim, print() exibiu esses valores.


15. Calcule a transformada de Fourier inversa de um sinal complexo gerado aleatoriamente.

In [ ]:
import numpy as np
from scipy.fft import ifft

sinal=np.random.random(10) + 1j * np.random.random(10)
transformadaInversa=ifft(sinal)  # Calcula a transformada inversa de Fourier

print(transformadaInversa)

[ 0.36922422+0.58996676j -0.02822907-0.15093814j -0.05552433-0.10738464j
 -0.13936567+0.0223461j  -0.02376824-0.04467727j -0.0482624 -0.04807019j
 -0.02193614-0.03164566j -0.06341195-0.07388332j  0.15257623+0.12704316j
  0.05244841+0.06439728j]


Um array sinal foi criado com 10 números aleatórios reais e imaginários, utilizando 1j para representar a parte imaginária. Depois, ifft() foi utilizada para calcular a Transformada Inversa de Fourier, convertendo os valores do domínio da frequência de volta para o domínio original. O resultado foi armazenado em transformadaInversa e exibida.


16. Resolva a equação diferencial de segunda ordem d²y/dx² + y = 0, com condições iniciais y(0) = 1 e y'(0) = 0.

In [ ]:
from scipy.integrate import solve_ivp

def equacao(x, y):
    return [y[1], -y[0]]

resultado=solve_ivp(equacao, [0, 10], [1, 0])  # Resolve a equação diferencial com as condições iniciais

print(resultado.y)

[[ 1.00000000e+00  9.99999501e-01  9.99939621e-01  9.93858100e-01
   7.24709764e-01 -1.22607648e-01 -8.96412983e-01 -8.66881284e-01
  -1.33005579e-01  7.61809510e-01  9.67792753e-01  3.37808419e-01
  -6.01037671e-01 -9.99858424e-01 -8.37545242e-01]
 [ 0.00000000e+00 -9.99000833e-04 -1.09887898e-02 -1.10661995e-01
  -6.89037713e-01 -9.92423098e-01 -4.43138753e-01  4.98428062e-01
   9.91048308e-01  6.47700170e-01 -2.51430149e-01 -9.41118675e-01
  -7.99102741e-01  7.31642727e-03  5.46146478e-01]]


Uma função foi criada para representar a equação diferencial, retornando os valores das derivadas de y. Depois, solve_ivp() foi utilizada para resolver a equação no intervalo de 0 a 10, começando com as condições iniciais [1, 0]. O resultado foi armazenado na variável resultado, e resultado.y contém os valores calculados para as soluções ao longo do intervalo.

17. Encontre a raiz cúbica de 27 utilizando SciPy.

In [ ]:
from scipy.special import cbrt

raiz=cbrt(27)  # Calcula a raiz cúbica de 27

print(raiz)

3.0


A função cbrt() foi utilizada para calcular a raiz cúbica de 27. O resultado foi armazenado na variável raiz e depois exibido utilizando print(). O resultado será 3, pois 3³ = 27 e a conta será mais exata do que elevar 3 a 1/3.


18. Interpole os valores da função f(x) = x**2 nos pontos [1, 2, 3, 4, 5] utilizando spline cúbica.

In [ ]:
from scipy.interpolate import CubicSpline
x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

spline=CubicSpline(x, y)  # Cria a spline cúbica
resultado=spline(2.5)  # Avalia a spline em x = 2.5

print(resultado)

6.25


Os valores de x e y foram definidos para representar pontos conhecidos. Depois, CubicSpline() criou uma interpolação por spline cúbica usando esses pontos. Em seguida, spline(2.5) calculou um valor aproximado de y para x = 2.5, utilizando a curva criada entre os pontos conhecidos. O resultado foi armazenado em resultado e exibido utilizando print().


19. Realize a transformada de Fourier de um sinal discreto composto por senos e cossenos.

In [ ]:
import numpy as np
from scipy.fft import fft

x=np.arange(100)
sinal=np.sin(x) + np.cos(x)  # Define o sinal composto por seno e cosseno
transformada=fft(sinal)  # Calcula a transformada de Fourier

print(transformada)

[-1.54128531e-02-0.00000000e+00j -1.68675566e-02+4.41750857e-02j
 -2.13019910e-02+8.93296254e-02j -2.89357650e-02+1.36523123e-01j
 -4.01657221e-02+1.86989351e-01j -5.56201220e-02+2.42263368e-01j
 -7.62537498e-02+3.04371176e-01j -1.03513323e-01+3.76136023e-01j
 -1.39633285e-01+4.61708122e-01j -1.88192368e-01+5.67546769e-01j
 -2.55238176e-01+7.04392444e-01j -3.51787610e-01+8.91640655e-01j
 -5.00161831e-01+1.16841296e+00j -7.53361380e-01+1.62740663e+00j
 -1.27513447e+00+2.55476709e+00j -2.94480549e+00+5.48665174e+00j
  3.49814543e+01-6.07513517e+01j  2.97142194e+00-4.81977519e+00j
  1.67649926e+00-2.54425254e+00j  1.22294500e+00-1.73895736e+00j
  9.92704368e-01-1.32417591e+00j  8.53957727e-01-1.06959240e+00j
  7.61551392e-01-8.96289744e-01j  6.95831147e-01-7.69898663e-01j
  6.46871199e-01-6.73047146e-01j  6.09119439e-01-5.96005941e-01j
  5.79228667e-01-5.32899632e-01j  5.55061813e-01-4.79968564e-01j
  5.35191107e-01-4.34693672e-01j  5.18626927e-01-3.95322578e-01j
  5.04662187e-01-3.605975

Um array x foi criado com os números de 0 a 99 utilizando np.arange(). Depois, o sinal foi criado somando as funções seno e cosseno aplicadas aos valores de x. Em seguida, fft() calculou a Transformada de Fourier desse sinal, transformando os dados do domínio do tempo em componentes de frequência. O resultado foi armazenado na variável transformada e exibido utilizando print().


20. Resolva um sistema de equações lineares com três variáveis utilizando SciPy.

In [ ]:
from scipy.linalg import solve
a=[
    [1, 2, 1],
    [2, 1, 3],
    [3, 2, 2]
]

b=[8, 13, 13]  # Define o vetor dos termos independentes

resultado = solve(a, b)  # Resolve o sistema linear

print(resultado)

[1. 2. 3.]


Uma matriz a foi criada contendo os coeficientes das três equações do sistema linear, enquanto b foi criado contendo os valores dos termos independentes. Depois, solve() foi utilizado para resolver o sistema de equações usando a matriz a e o vetor b. O resultado foi armazenado na variável resultado, contendo os valores das incógnitas que satisfazem as três equações. Por fim, print() exibiu a solução encontrada.

## Exercícios Pandas

1. Crie um DataFrame contendo as colunas Produto, Preço e Quantidade
com 5 produtos.


In [ ]:
import pandas as pd

tabela={'Produto': ['Mouse', 'Teclado', 'Monitor', 'Notebook', 'MousePad'],
        'Preço': [50, 65, 500, 3500, 20],
        'Quantidade': [5, 2, 2, 5, 20]} # Cria um dicionário com os dados dos produtos

df=pd.DataFrame(tabela) # Converte o dicionário em um DataFrame
print(df)

    Produto  Preço  Quantidade
0     Mouse     50           5
1   Teclado     65           2
2   Monitor    500           2
3  Notebook   3500           5
4  MousePad     20          20


Um dicionário chamado tabela foi criado contendo as informações dos produtos, preços e quantidades. Depois, a função pd.DataFrame()foi utilizada para transformar o dicionário em um DataFrame, organizando os dados em linhas e colunas e armazenando o resultado na variável df.

2. Leia um arquivo Excel chamado vendas.xlsx e exiba as 10 primeiras linhas.


In [ ]:
import pandas as pd
from google.colab import files

files.upload() # Abre o seletor de arquivos para enviar o vendas.xlsx

df=pd.read_excel('vendas.xlsx') # Lê o arquivo Excel e transforma em DataFrame

print(df.head(10))  # Exibe as 10 primeiras linhas

A função files.upload() da biblioteca do Google Colab foi utilizada para permitir o envio do arquivo vendas.xlsx do computador para o ambiente do Colab. Depois, a função pd.read_excel() foi utilizada para ler o arquivo Excel e transformar seus dados em um DataFrame, armazenado na variável df. Por fim, a função df.head(10) foi utilizada para exibir as 10 primeiras linhas do DataFrame.


3. Filtre um DataFrame para exibir apenas os valores onde a coluna Preço é maior que 100.

In [ ]:
import pandas as pd

valores_maiores100=df.loc[df['Preço'] > 100,'Preço']  # Seleciona apenas os preços maiores que 100

print(valores_maiores100)

2     500
3    3500
Name: Preço, dtype: int64


A condição df['Preço'] > 100 foi utilizada para verificar quais valores da coluna Preço são maiores que 100. Depois, a função .loc[] foi utilizada para selecionar somente os valores da coluna Preço que atendem a essa condição, armazenando o resultado na variável valores_maiores100.


4. Adicione uma coluna chamada Desconto ao DataFrame com 10% de desconto para todos os produtos.

In [ ]:
import pandas as pd

df['Desconto 10%']=df['Preço'] / 10 # Cria a coluna Desconto 10% com 10% do preço

print(df)

    Produto  Preço  Quantidade  Desconto 10%
0     Mouse     50           5           5.0
1   Teclado     65           2           6.5
2   Monitor    500           2          50.0
3  Notebook   3500           5         350.0
4  MousePad     20          20           2.0


Uma nova coluna chamada Desconto 10% foi criada no DataFrame, utilizando os valores da coluna Preço divididos por 10 para calcular 10% de cada preço. O resultado foi armazenado na nova coluna Desconto 10%.


5. Remova as linhas do DataFrame que contenham valores nulos.

In [ ]:
import pandas as pd

df=df.dropna()

A função dropna() foi utilizada para remover as linhas do DataFrame que possuem valores nulos, e o resultado foi armazenado novamente na variável df, atualizando o DataFrame sem essas linhas.

6. Ordene o DataFrame pela coluna Produto em ordem alfabética.


In [ ]:
import pandas as pd

df=df.sort_values(by='Produto') # Ordena as linhas pela coluna Produto

print(df)

    Produto  Preço  Quantidade  Desconto 10%
2   Monitor    500           2          50.0
0     Mouse     50           5           5.0
4  MousePad     20          20           2.0
3  Notebook   3500           5         350.0
1   Teclado     65           2           6.5


A função sort_values() foi utilizada para ordenar as linhas do DataFrame de acordo com os valores da coluna Produto. O parâmetro by='Produto' indica que a coluna Produto será utilizada como referência para a ordenação. Por padrão, os valores são organizados em ordem crescente, ou seja, em ordem alfabética. O resultado foi armazenado novamente na variável df e depois exibido com print().


7. Crie uma nova coluna chamada Total que seja o produto entre as colunas Preço e Quantidade.


In [ ]:
import pandas as pd

df['Total']=df['Preço'] / df['Quantidade']  # Cria a coluna Total multiplicando Preço por Quantidade

print(df)

    Produto  Preço  Quantidade  Desconto 10%  Total
2   Monitor    500           2          50.0  250.0
0     Mouse     50           5           5.0   10.0
4  MousePad     20          20           2.0    1.0
3  Notebook   3500           5         350.0  700.0
1   Teclado     65           2           6.5   32.5


A coluna Total foi criada utilizando a divisão dos valores da coluna Preço pelos valores correspondentes da coluna Quantidade, armazenando o resultado em uma nova coluna chamada Total

8.  Agrupe o DataFrame pela coluna Categoria e calcule o total de produtos por categoria

In [ ]:
import pandas as pd

df['Categoria']=['Hardware','Hardware','Acessório','Hardware','Hardware'] # Adiciona a coluna Categoria

total_por_categoria=df.groupby('Categoria')['Produto'].count()  # Agrupa por Categoria e conta os produtos

print(total_por_categoria)

Categoria
Acessório    1
Hardware     4
Name: Produto, dtype: int64


Uma nova coluna chamada Categoria foi criada no DataFrame, recebendo uma categoria para cada produto. Depois, a função groupby() foi utilizada para agrupar os produtos de acordo com a categoria, e ['Produto'].count() foi utilizada para contar quantos produtos existem em cada categoria. O resultado foi armazenado na variável total_por_categoria e exibido com print().

9.  Exporte o DataFrame resultante para um arquivo CSV chamado resultados.csv.

In [ ]:
import pandas as pd

df.to_csv('resultados.csv', index=False) # Salva o DataFrame em CSV sem o índice

print("Arquivo 'resultados.csv' gerado com sucesso.")

from google.colab import files # Importa a função files do módulo google.colab

files.download('resultados.csv') # Baixa o arquivo CSV gerado

Arquivo 'resultados.csv' gerado com sucesso.


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

A função to_csv() foi utilizada para salvar o DataFrame em um arquivo CSV chamado resultados.csv, utilizando index=False para não salvar os índices do DataFrame no arquivo. Depois, a função files.download() foi utilizada para baixar o arquivo gerado para o computador.

10. Leia um arquivo CSV, renomeie as colunas e exiba as 5 últimas linhas do
DataFrame.

In [ ]:
import pandas as pd

df=pd.read_csv('resultados.csv') # Lê o arquivo CSV

df.columns=['Produtos', 'Preços', 'Qtd', 'Desconto', 'Total/Qtd', 'Categorias']  # Lenomeia as colunas

print(df.tail(5))

   Produtos  Preços  Qtd  Desconto  Total/Qtd Categorias
0   Monitor     500    2      50.0      250.0   Hardware
1     Mouse      50    5       5.0       10.0   Hardware
2  MousePad      20   20       2.0        1.0  Acessório
3  Notebook    3500    5     350.0      700.0   Hardware
4   Teclado      65    2       6.5       32.5   Hardware


Um arquivo CSV chamado resultados.csv foi lido utilizando a função pd.read_csv() e armazenado no DataFrame df. Depois, os nomes das colunas foram substituídos pelos nomes definidos na lista, utilizando df.columns. Por fim, a função df.tail(5) foi utilizada para selecionar as 5 últimas linhas do DataFrame, que foram exibidas utilizando print().


11. Preencha os valores nulos de uma coluna numérica com a mediana dessa coluna.

In [ ]:
import pandas as pd

df['Preços']=df['Preços'].fillna(df['Preços'].median())  # Substitui nulos pela mediana da coluna Preço

print(df)

   Produtos  Preços  Qtd  Desconto  Total/Qtd Categorias
0   Monitor     500    2      50.0      250.0   Hardware
1     Mouse      50    5       5.0       10.0   Hardware
2  MousePad      20   20       2.0        1.0  Acessório
3  Notebook    3500    5     350.0      700.0   Hardware
4   Teclado      65    2       6.5       32.5   Hardware


A coluna Preço foi selecionada e os valores nulos foram substituídos pela mediana dessa mesma coluna utilizando fillna() e median(). Assim, os valores que estavam vazios recebem o valor central dos preços existentes. Por fim, o DataFrame atualizado foi exibido utilizando print().


12. Verifique quais colunas de um DataFrame contém valores duplicados.

In [ ]:
import pandas as pd

colunasDuplicadas=df.columns[df.T.duplicated()]  # Transpõe e verifica colunas com valores repetidos

print(colunasDuplicadas)

Index([], dtype='object')


O DataFrame foi transposto utilizando df.T, fazendo com que as colunas se tornem linhas. Depois, duplicated() foi utilizada para verificar quais dessas linhas possuem valores duplicados. A variável df.columns foi utilizada para retornar os nomes das colunas que foram identificadas como duplicadas. O resultado foi armazenado em colunasDuplicadas e exibido utilizando print().


13. Crie uma tabela dinâmica a partir do DataFrame, calculando a soma de Quantidade por Categoria.

In [ ]:
import pandas as pd

tabelaDinamica=pd.pivot_table(df, values='Qtd', index='Categorias', aggfunc='sum')  # Cria a tabela dinâmica

print(tabelaDinamica)

            Qtd
Categorias     
Acessório    20
Hardware     14


O DataFrame foi utilizado para criar uma tabela dinâmica com pivot_table(). A coluna Quantidade foi definida como os valores que serão calculados, enquanto Categoria foi utilizada para organizar os dados em grupos. O parâmetro aggfunc='sum' faz com que as quantidades sejam somadas dentro de cada categoria. O resultado foi armazenado na variável tabelaDinamica e exibido utilizando print().


14. Mescle dois DataFrames baseados em uma coluna comum chamada ID utilizando um join.

In [ ]:
import pandas as pd

df1=pd.DataFrame({
    'ID': [1, 2, 3],
    'Produto': ['Mouse', 'Teclado', 'Monitor']
})  # Cria o primeiro DataFrame com ID e Produto

df2=pd.DataFrame({
    'ID': [1, 2, 3],
    'Preço': [50, 65, 500]
})  # Cria o segundo DataFrame com ID e Preço

resultado=df1.merge(df2, on='ID')  # Faz o merge pela coluna ID

print(resultado)

   ID  Produto  Preço
0   1    Mouse     50
1   2  Teclado     65
2   3  Monitor    500


Dois DataFrames foram criados, sendo o primeiro com as colunas ID e Produto e o segundo com as colunas ID e Preço. Depois, merge() foi utilizado para juntar os dois DataFrames através da coluna ID. Como os dois possuem os mesmos IDs, as informações de Produto e Preço foram combinadas em um único DataFrame. Por fim, o resultado foi armazenado na variável resultado e exibido utilizando print().


15. Crie um DataFrame com dados faltantes e use a interpolação linear para preenchê-los.

In [ ]:
import pandas as pd

dados={
    'Vendas': [100, None, 200, None, 300]
}  # Cria um dicionário com valores nulos

dataFrame=pd.DataFrame(dados)  # Transforma o dicionário em DataFrame

dataFrame=dataFrame.interpolate()  # Preenche os nulos por interpolação linear

print(dataFrame)

   Vendas
0   100.0
1   150.0
2   200.0
3   250.0
4   300.0


Um dicionário foi criado com uma coluna chamada Vendas contendo alguns valores e valores nulos representados por None. Depois, pd.DataFrame() transformou o dicionário em um DataFrame. Em seguida, df.interpolate() preencheu os valores nulos utilizando interpolação linear, calculando valores intermediários com base nos valores conhecidos antes e depois. Por fim, print() exibiu o DataFrame com os valores preenchidos.


16. Crie um gráfico de barras a partir de um DataFrame usando a biblioteca Pandas.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df.plot(kind='bar', x='Produtos', y='Preços')  # Cria o gráfico de barras
plt.show()

O DataFrame foi utilizado para criar um gráfico de barras com plot(), definindo a coluna Produto no eixo X e a coluna Preço no eixo Y. O parâmetro kind='bar' define que o gráfico será de barras. Depois, plt.show() foi utilizado para exibir o gráfico.


17. Adicione uma coluna ao DataFrame que calcule o imposto (5%) sobre o valor da coluna Total.

In [ ]:
import pandas as pd

df['Imposto']=df['Total'] * 0.05  # Cria a coluna Imposto com 5% de Total
print(df)

Uma nova coluna chamada Imposto foi criada no DataFrame. Para cada linha, o valor da coluna Total foi multiplicado por 0.05, calculando 5% do total. O resultado foi armazenado na nova coluna Imposto e o DataFrame completo foi exibido utilizando print().


18. Exiba apenas as linhas de um DataFrame onde o nome do produto começa com a letra ”B”.

In [ ]:
import pandas as pd

produtos_b=df[df['Produtos'].str.startswith('B')]  # Filtra produtos que começam com B

print(produtos_b)

O DataFrame foi filtrado utilizando a coluna Produto para verificar quais valores começam com a letra B. O método startswith() foi utilizado para fazer essa verificação e retornar apenas os produtos que atendem à condição. O resultado foi armazenado na variável produtos_b e exibido utilizando print().


19. Crie um DataFrame a partir de um dicionário de listas e calcule a média de cada coluna numérica.

In [ ]:
import pandas as pd

dados={'Nota1': [8, 7, 9], 'Nota2': [10, 6, 8], 'Nota3': [9, 8, 7]}

df=pd.DataFrame(dados)  # Transforma o dicionário em DataFrame

print(df.mean())

Um dicionário foi criado com três colunas de notas e seus respectivos valores. Depois, pd.DataFrame() transformou o dicionário em um DataFrame. Em seguida, df.mean() calculou a média dos valores de cada coluna. Por fim, print() exibiu as médias das três notas.


20. Agrupe os dados por uma coluna categórica e calcule a mediana de uma coluna numérica.

In [ ]:
import pandas as pd

medianaCategoria=df.groupby('Categoria')['Preço'].median()  # Agrupa por Categoria e calcula a mediana de Preço

print(medianaCategoria)

O DataFrame foi agrupado pela coluna Categoria utilizando groupby(), e depois a mediana dos valores da coluna Preço foi calculada para cada categoria utilizando median(). O resultado foi armazenado na variável medianaCategoria e exibido utilizando print().


## Exercícios MatPlotLib

1. Crie um gráfico de linha para a função y = x 3 no intervalo de x = −10 até x = 10.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x=np.arange(-10, 11)  # Gera valores de x de -10 a 10
y=x**3

plt.plot(x, y)  # Cria o gráfico de linha
plt.show()  # Exibe o gráfico

Um array x foi criado com valores inteiros de -10 a 10 utilizando np.arange(). Depois, y foi calculado elevando cada valor de x ao cubo, representando a função y = x³. Em seguida, plt.plot() foi utilizado para criar o gráfico de linha com os valores de x e y. Por fim, plt.show() exibiu o gráfico.


2. Plote um gráfico de dispersão para 100 pontos aleatórios com uma paleta de cores baseada nos valores de y.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x=np.random.rand(100)  # Gera 100 valores aleatórios para x
y=np.random.rand(100)  # Gera 100 valores aleatórios para y

plt.scatter(x, y, c=y)  # Cria o gráfico de dispersão com cores baseadas em y
plt.show()

Dois arrays foram criados com 100 valores aleatórios entre 0 e 1 utilizando np.random.rand(), sendo um para os valores de x e outro para os valores de y. Depois, plt.scatter() foi utilizada para criar o gráfico de dispersão, usando x e y para definir a posição dos pontos. O parâmetro c=y faz com que a cor de cada ponto seja definida de acordo com seu valor de y. Por fim, plt.show() exibiu o gráfico.


3. Gere um histograma para 500 números inteiros gerados aleatoriamente entre 0 e 100.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

numeros=np.random.randint(0, 101, 500)

plt.hist(numeros)  # Cria o histograma
plt.show()

Um array foi criado com 500 números inteiros aleatórios entre 0 e 100 utilizando np.random.randint(). Depois, plt.hist() foi utilizada para criar um histograma, agrupando os números em intervalos para mostrar a distribuição dos valores. Por fim, plt.show() exibiu o gráfico.


4. Crie um gráfico de barras para 5 categorias com valores diferentes, colorindo cada barra de uma cor diferente.

In [ ]:
import matplotlib.pyplot as plt

categorias=['A', 'B', 'C', 'D', 'E']  # Define as categorias
valores=[10, 20, 15, 25, 30]  # Define os valores de cada categoria

plt.bar(categorias, valores, color=['red', 'blue', 'green', 'yellow', 'purple'])  # Cria o gráfico de barras colorido
plt.show()

Duas listas foram criadas, uma contendo as categorias A, B, C, D e E e outra contendo os valores correspondentes a cada categoria. Depois, plt.bar() foi utilizada para criar o gráfico de barras, utilizando as categorias no eixo X e os valores no eixo Y. O parâmetro color foi utilizado para definir uma cor diferente para cada barra. Por fim, plt.show() exibiu o gráfico.


5. Faça um gráfico de pizza para representar as porcentagens de quatro setores de mercado com rótulos personalizados.

In [ ]:
import matplotlib.pyplot as plt

valores=[30, 25, 20, 25]  # Define os valores dos setores
setores=['Tecnologia', 'Saude', 'Varejo', 'Indústria']  # Define os rótulos

plt.pie(valores, labels=setores)  # Cria o gráfico de pizza
plt.show()

Uma lista de valores foi criada para representar a quantidade de cada setor, e outra lista foi criada para definir os nomes correspondentes a cada valor. Depois, plt.pie() foi utilizada para criar o gráfico de pizza, utilizando os valores e os rótulos dos setores. Por fim, plt.show() exibiu o gráfico.


6. Plote dois gráficos de linha em subplots diferentes: y1 = e^x e y2 = log(x).

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x=np.arange(1, 11)

plt.subplot(2, 1, 1)  # Define o primeiro subplot (linha 1)
plt.plot(x, np.exp(x))  # Plota y1 = e^x

plt.subplot(2, 1, 2)  # Define o segundo subplot (linha 2)
plt.plot(x, np.log(x))  # Plota y2 = log(x)

plt.show()

Um array x foi criado com os números de 1 a 10 utilizando np.arange(). Depois, plt.subplot() foi utilizado para dividir a figura em 2 linhas e 1 coluna, criando dois gráficos. No primeiro subplot, plt.plot() criou o gráfico da função eˣ. No segundo subplot, plt.plot() criou o gráfico da função log(x). Por fim, plt.show() exibiu os dois gráficos na mesma figura.


7. Crie um gráfico de dispersão com tamanho dos pontos variando de acordo com os valores de y.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x=np.random.rand(100)
y=np.random.rand(100)

plt.scatter(x, y, s=y*500)  # Cria o gráfico de dispersão com tamanho proporcional a y
plt.show()

Dois arrays x e y foram criados com 100 valores aleatórios entre 0 e 1 utilizando np.random.rand(). Depois, plt.scatter() foi utilizado para criar o gráfico de dispersão, utilizando x e y para definir a posição dos pontos. O parâmetro s=y*500 faz com que o tamanho de cada ponto seja proporcional ao valor correspondente de y. Por fim, plt.show() exibiu o gráfico.


8. Plote um gráfico de linha com intervalos de confiançaa (sombramento) para a função y = sin(x).

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x=np.linspace(0, 10, 100)
y=np.sin(x)  # Calcula y = sin(x)

plt.plot(x, y)  # Plota a curva principal
plt.fill_between(x, y-0.2, y+0.2, alpha=0.3)  # Adiciona sombreamento ao redor da curva
plt.show()

Um array x foi criado com 100 valores igualmente espaçados entre 0 e 10 utilizando np.linspace(), e y foi calculado utilizando np.sin(x), representando a função seno. Depois, plt.plot() foi utilizado para criar a curva principal. Em seguida, plt.fill_between() adicionou um sombreamento entre os valores y - 0.2 e y + 0.2, criando uma faixa ao redor da curva. Por fim, plt.show() exibiu o gráfico.


9. Adicione título, rótulos e uma grade personalizada a um gráfico de linha.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x=np.arange(1, 11)
plt.plot(x, x**2)  # Plota y = x^2

plt.title('Gráfico de linha')
plt.xlabel('x')  # Adiciona rótulo do eixo x
plt.ylabel('y')  # Adiciona rótulo do eixo y
plt.grid()  # Adiciona grade

plt.show()

Um array x foi criado com os números de 1 a 10 utilizando np.arange(). Depois, plt.plot() foi utilizado para criar o gráfico de linha, calculando os valores de y elevando cada valor de x ao quadrado. Em seguida, plt.title() definiu o título, enquanto plt.xlabel() e plt.ylabel() identificaram os eixos. A função plt.grid() adicionou uma grade ao gráfico e plt.show() exibiu o resultado.


10. Plote três gráficos de linha em um único gráfico, cada um com uma cor e estilo de linha diferentes.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x=np.arange(1, 11)

plt.plot(x, x, color='red', linestyle='-')  # Plota y = x com linha sólida vermelha
plt.plot(x, x**2, color='blue', linestyle='--')  # Plota y = x^2 com linha tracejada azul
plt.plot(x, x**3, color='green', linestyle=':')  # Plota y = x^3 com linha pontilhada verde

plt.show()

11.  Crie um gráfico de barras empilhadas para três categorias com três grupos de valores.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

categorias = ['A', 'B', 'C']

valores1 = [3, 5, 4]
valores2 = [2, 4, 3]
valores3 = [5, 7, 6]

# Cria as primeiras barras, que ficam na base do gráfico
plt.bar(categorias, valores1, label='Grupo 1')

# bottom coloca o Grupo 2 acima dos valores do Grupo 1
plt.bar(categorias, valores2, bottom=valores1, label='Grupo 2')

# Soma os dois primeiros grupos para colocar o Grupo 3 acima deles
plt.bar(categorias, valores3, bottom=np.array(valores1) + np.array(valores2), label='Grupo 3')

plt.title('Gráfico de Barras Empilhadas')
plt.xlabel('Categorias')
plt.ylabel('Valores')

plt.legend()  # Exibe a legenda dos grupos
plt.show()    # Exibe o gráfico

Três listas de valores foram criadas para representar os três grupos de dados, sendo cada posição relacionada às categorias A, B e C. Depois, plt.bar() foi utilizada para criar as barras do Grupo 1, que ficam na base do gráfico. Em seguida, o parâmetro bottom=valores1 foi utilizado para colocar o Grupo 2 acima dos valores do Grupo 1. Para posicionar o Grupo 3, os valores dos Grupos 1 e 2 foram somados utilizando np.array(), fazendo com que o Grupo 3 começasse acima dos dois grupos anteriores. Depois, plt.title() foi utilizado para definir o título, enquanto plt.xlabel() e plt.ylabel() foram utilizados para nomear os eixos. A função plt.legend() adicionou a legenda dos grupos e plt.show() exibiu o gráfico.

12.  Plote um gráfico de linha com uma funções quadrática e ajuste os limites
do eixo para focar nos valores x = -5 a x = 5.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Gera 100 valores igualmente espaçados entre -5 e 5
x = np.linspace(-5, 5, 100)

# Calcula o valor de y para cada valor de x
y = x ** 2

# Define os limites do eixo X
plt.xlim(-5, 5)

# Cria o gráfico de linha
plt.plot(x, y)

plt.title('Gráfico de Linha')
plt.xlabel('Eixo X')
plt.ylabel('Eixo Y')

plt.show()

Um array x foi criado com 100 valores igualmente espaçados entre -5 e 5 utilizando np.linspace(). Depois, a variável y foi criada elevando cada valor de x ao quadrado, formando a função y = x². Em seguida, plt.xlim() foi utilizada para definir os limites do eixo X entre -5 e 5. A função plt.plot() foi utilizada para criar o gráfico de linha utilizando os valores de x e y. Depois, plt.title() definiu o título do gráfico, enquanto plt.xlabel() e plt.ylabel() foram utilizados para identificar os eixos X e Y. Por fim, plt.show() exibiu o gráfico.

13. Gere um gráfico de dispersão 3D para 100 pontos aleatórios utilizando Matplotlib.


In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Gera 100 valores aleatórios para cada eixo
x = np.random.rand(100)
y = np.random.rand(100)
z = np.random.rand(100)

# Cria uma figura e adiciona um eixo 3D
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Cria os pontos de dispersão usando os três eixos
ax.scatter(x, y, z)

ax.set_title('Gráfico de Dispersão 3D')
ax.set_xlabel('Eixo X')
ax.set_ylabel('Eixo Y')
ax.set_zlabel('Eixo Z')

plt.show()

Três arrays foram criados com 100 números aleatórios entre 0 e 1, sendo cada array responsável por representar um dos três eixos do gráfico. Depois, uma figura foi criada utilizando plt.figure() e um eixo tridimensional foi adicionado utilizando fig.add_subplot(), com projection='3d' para definir que o gráfico terá três dimensões. Em seguida, ax.scatter() foi utilizado para criar o gráfico de dispersão, utilizando os valores de x, y e z para definir a posição de cada ponto. Como foram gerados 100 valores para cada eixo, o gráfico possui 100 pontos. Depois, set_title() foi utilizado para definir o título, enquanto set_xlabel(), set_ylabel() e set_zlabel() foram utilizados para identificar os eixos X, Y e Z. Por fim, plt.show() exibiu o gráfico.

14. Crie um gráfico de barras horizontal para 4 categorias com valores gerados
aleatoriamente.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

categorias = ['A', 'B', 'C', 'D']

# Gera 4 valores inteiros aleatórios entre 1 e 100
valores = np.random.randint(1, 101, 4)

# Cria o gráfico de barras
plt.bar(categorias, valores)

plt.title('Gráfico de Barras')
plt.xlabel('Categorias')
plt.ylabel('Valores')

plt.show()

Um array com 4 valores inteiros aleatórios entre 1 e 100 foi criado utilizando np.random.randint(), sendo cada valor relacionado a uma das quatro categorias definidas. Depois, plt.bar() foi utilizada para criar o gráfico de barras, utilizando as categorias no eixo X e os valores aleatórios no eixo Y. Em seguida, plt.title() foi utilizada para definir o título do gráfico, enquanto plt.xlabel() e plt.ylabel() foram utilizadas para identificar os eixos. Por fim, plt.show() exibiu o gráfico.

15. Plote a função y = 1/x com x variando de 1 a 100.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Gera 1000 pontos igualmente espaçados entre 1 e 100
x = np.linspace(1, 100, 1000)

# Calcula o valor de y para cada valor de x
y = 1 / x

# Cria o gráfico de linha
plt.plot(x, y, label='y = 1/x')

plt.title('Gráfico da Função Inversa (y = 1/x)')
plt.xlabel('Eixo X (Valores de 1 a 100)')
plt.ylabel('Eixo Y (Valores de 1/x)')

# Adiciona uma grade e a legenda ao gráfico
plt.grid(True)
plt.legend()

plt.show()

Um array x foi criado com 1000 valores igualmente espaçados entre 1 e 100 utilizando np.linspace(), permitindo gerar uma curva mais suave no gráfico. Depois, um array y foi criado calculando 1 dividido por cada valor de x, representando a função y = 1/x. Em seguida, plt.plot() foi utilizado para criar o gráfico de linha, utilizando x no eixo horizontal e y no eixo vertical. O parâmetro label foi utilizado para definir o nome da função que aparecerá na legenda. Depois, plt.title() definiu o título do gráfico, enquanto plt.xlabel() e plt.ylabel() identificaram os eixos X e Y. A função plt.grid() adicionou uma grade para facilitar a visualização dos valores no gráfico e plt.legend() exibiu a legenda da função. Por fim, plt.show() exibiu o gráfico.

16. Crie um gráfico de linha com títulos para cada eixo e adicione um rótulo
de texto no ponto x = 5.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Gera 100 pontos entre 0 e 10 para criar uma curva suave
x = np.linspace(0, 10, 100)

# Calcula y para cada valor de x
y = x**2

# Cria o gráfico de linha
plt.plot(x, y, color='purple', label='y = x^2')

plt.title('Gráfico de Linha com Rótulo no Ponto x = 5')
plt.xlabel('Eixo X (Valores)')
plt.ylabel('Eixo Y (Valores de x^2)')

# Destaca o ponto x = 5 e y = 25
plt.plot(5, 25, 'ro')

# Adiciona um texto próximo ao ponto destacado
plt.text(5.3, 23, 'Ponto x = 5 (y = 25)', color='red', fontsize=10, fontweight='bold')

plt.grid(True)
plt.legend()

plt.show()

Um array x foi criado com 100 valores igualmente espaçados entre 0 e 10 utilizando np.linspace(), e depois y foi calculado elevando cada valor de x ao quadrado. Em seguida, plt.plot() criou o gráfico da função y = x². O ponto (5, 25) foi destacado usando plt.plot(5, 25, 'ro'), e plt.text() adicionou um texto próximo a esse ponto. Por fim, plt.grid() adicionou uma grade, plt.legend() adicionou a legenda e plt.show() exibiu o gráfico.


17. Plote um gráfico de linha e salve-o como um arquivo PDF.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Gera 100 pontos igualmente espaçados entre 0 e 10
x = np.linspace(0, 10, 100)
y = np.sin(x)

# Cria o gráfico da função seno
plt.plot(x, y, color='blue', label='y = sen(x)')

plt.title('Gráfico de Linha - Função Seno')
plt.xlabel('Eixo X')
plt.ylabel('Eixo Y')
plt.grid(True)
plt.legend()

# Salva o gráfico em formato PDF
plt.savefig('grafico_linha.pdf', format='pdf')

# Fecha o gráfico após salvá-lo
plt.close()

Um array x foi criado com 100 valores igualmente espaçados entre 0 e 10 utilizando np.linspace(), e y foi calculado utilizando np.sin(x), representando a função seno. Depois, plt.plot() criou o gráfico da função. Os comandos plt.title(), plt.xlabel() e plt.ylabel() adicionaram o título e os nomes dos eixos, enquanto plt.grid() adicionou a grade e plt.legend() adicionou a legenda. Por fim, plt.savefig() salvou o gráfico como um arquivo PDF e plt.close() fechou o gráfico após o salvamento.

18. Crie um gráfico de barras com valores positivos e negativos e use diferentes
cores para cada tipo de valor.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Define os valores positivos e negativos para cada mês
categorias = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago']
valores = np.array([12, -7, 15, -3, 8, -10, 5, -2])

# Define verde para valores positivos e vermelho para negativos
cores = ['green' if v >= 0 else 'red' for v in valores]

# Cria o gráfico de barras usando as cores definidas
plt.bar(categorias, valores, color=cores, edgecolor='black', linewidth=0.7)

# Cria uma linha horizontal no valor 0
plt.axhline(0, color='black', linewidth=1.2)

plt.title('Resultados Mensais: Lucros e Prejuízos (Jan a Ago)')
plt.xlabel('Meses')
plt.ylabel('Valores (em R$ Milhares)')
plt.grid(True, linestyle='--', alpha=0.5)

plt.show()

Um array com valores positivos e negativos foi criado para representar os resultados de cada mês. Depois, uma lista de cores foi criada utilizando uma condição que define verde para valores maiores ou iguais a zero e vermelho para valores negativos. Em seguida, plt.bar() criou o gráfico de barras utilizando essas cores. A função plt.axhline() adicionou uma linha horizontal no valor zero para facilitar a identificação entre lucros e prejuízos. Por fim, os títulos e nomes dos eixos foram adicionados, plt.grid() criou uma grade e plt.show() exibiu o gráfico.

19. Plote um gráfico de linha com duas séries e adicione uma legenda para
diferenciá-las.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Gera 100 pontos igualmente espaçados entre 0 e 10
x = np.linspace(0, 10, 100)

# Calcula os valores das funções seno e cosseno
y1 = np.sin(x)
y2 = np.cos(x)

# Cria as duas linhas no mesmo gráfico
plt.plot(x, y1, label='Seno')
plt.plot(x, y2, label='Cosseno')

plt.title('Gráfico de Linhas com Múltiplas Séries')
plt.xlabel('Eixo X')
plt.ylabel('Eixo Y')

# Exibe os nomes das duas linhas na legenda
plt.legend()

plt.show()

Um array x foi criado com 100 valores igualmente espaçados entre 0 e 10 utilizando np.linspace(). Depois, dois arrays foram criados utilizando np.sin() e np.cos() para representar as funções seno e cosseno. Em seguida, plt.plot() foi utilizado duas vezes para criar as duas linhas no mesmo gráfico, utilizando label para identificar cada uma na legenda. Depois, plt.title(), plt.xlabel() e plt.ylabel() foram utilizados para adicionar o título e identificar os eixos. Por fim, plt.legend() exibiu a legenda e plt.show() mostrou o gráfico.

20. Adicione uma grade com espaçamento personalizado a um gráfico de linha
para y = x
2
.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Gera 200 pontos igualmente espaçados entre -10 e 10
x = np.linspace(-10, 10, 200)
y = x**2

# Cria o gráfico da função y = x²
plt.plot(x, y, color='blue', label='y = x^2')

# Define o espaçamento dos valores dos eixos
plt.xticks(np.arange(-10, 11, 2))
plt.yticks(np.arange(0, 101, 10))

# Adiciona a grade ao gráfico
plt.grid(True, linestyle='--', alpha=0.6, color='gray')

plt.title('Gráfico de y = x^2 com Grade Personalizada')
plt.xlabel('Eixo X (Espaçamento: 2)')
plt.ylabel('Eixo Y (Espaçamento: 10)')
plt.legend()

plt.show()

Um array x foi criado com 200 valores igualmente espaçados entre -10 e 10 utilizando np.linspace(), e y foi calculado elevando cada valor de x ao quadrado. Depois, plt.plot() criou o gráfico da função. Em seguida, plt.xticks() definiu os valores do eixo X com espaçamento de 2 em 2, enquanto plt.yticks() definiu os valores do eixo Y com espaçamento de 10 em 10. Para isso, np.arange() foi utilizado para gerar essas sequências. Depois, plt.grid() adicionou a grade seguindo os espaçamentos definidos. Por fim, foram adicionados o título, os nomes dos eixos e a legenda, e plt.show() exibiu o gráfico.

## Comentário Final


De modo geral, a atividade teve uma dificuldade normal. Eu não conhecia as bibliotecas utilizadas nos exercícios, mas o com o arquivo disponibilizado com os conteúdos e exemplos e algumas pesquisas foi tranquilo de aprender.
Tive mais dificuldade com a biblioteca SciPy, principalmente por envolver fórmulas matemáticas e cálculos com os quais eu não tinha muita familiaridade. Precisei pesquisar e estudar alguns conceitos para conseguir entender melhor os exercícios e aplicar as funções corretamente.
